let readlineSync = require('readline-sync');
let arregloMes = new Array (12);
arregloMes[0] = "Enero";
arregloMes[1] = "Febrero";
arregloMes[2] = "Marzo";
arregloMes[3] = "Abril";
arregloMes[4] = "Mayo";
arregloMes[5] = "Junio";
arregloMes[6] = "Julio";
arregloMes[7] = "Agosto";
arregloMes[8] = "Septiembre";
arregloMes[9] = "Octubre";
arregloMes[10] = "Novienbre";
arregloMes[11] = "Diciembre";
let nroMes = readlineSync.questionInt(`indique el numero de mes que le interesa`);
let indice = nroMes - 1;
console.log("el mes es",nroMes);